import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import SideBar from "@/app/components/layout/sidebar";
import Header from "@/app/components/layout/header";
import Footer from "@/app/components/layout/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex h-screen">
          <div className="flex-shrink-0 fixed top-0 left-0 h-full w-32 md:w-48 bg-white border-r border-gray-200">
            <SideBar />
          </div>
          <div className="ml-32 md:ml-48 flex-1">
            <Header />
            {/* full screen same bg color */}
            <main className="min-h-screen p-4 bg-gray-100" style={{ backgroundImage: "url('/images/berry.png')", backgroundRepeat: "repeat-y", backgroundSize: "100% auto" }}>
              {children}
            </main>
            <Footer />
          </div>
        </div>
      </body>
    </html>
  );
}
